CREATE TABLE "ee37_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ee37_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "ee37_submission" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(256) NOT NULL,
	"word" varchar(50) NOT NULL,
	"imageUrl" text,
	"imageName" varchar(256),
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE INDEX "name_idx" ON "ee37_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "submission_name_idx" ON "ee37_submission" USING btree ("name");